In [1]:
%load_ext autoreload
%autoreload 2
import scanpy as sc
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
cell_protein_df = pd.read_csv('../data/MIBI/raw/cell_protein_data.csv')
patient_df = pd.read_csv('../data/MIBI/raw/patient_info.csv')

In [3]:
import sys
import os
import numpy as np
from torch_geometric.loader import DataLoader

sys.path.append(os.path.abspath('../src'))
from utils.data_utils import split_dataset, split_indices
from dataset.placenta import PlacentaDatasetHypergraph
from dataset.extend import ExtendedDataset
from dataset.mibi import MIBIDataset, MIBISubsetHypergraph

def prepare_dataloaders(args):
    if args.dataset == 'mibi':
        dataset = MIBIDataset(data_folder=args.data_folder, k_hop=args.k_hop)

        ratios = [float(c) for c in args.train_val_test_ratio.split(':')]
        ratios = tuple([c / sum(ratios) for c in ratios])
        indices = list(range(len(dataset)))

        # NOTE: This is a hack to make sure all sets have all classes.
        all_class_subset1 = [0, 1, 4, 6]
        all_class_subset2 = [7, 8, 10, 11]
        all_class_subset3 = [12, 13, 14, 15]
        indices = list(set(indices) - set(all_class_subset1 + all_class_subset2 + all_class_subset3))
        adjusted_ratios = len(dataset) * np.array(ratios) - np.array([4, 4, 4])
        adjusted_ratios = tuple([c / sum(adjusted_ratios) for c in adjusted_ratios])
        train_indices, val_indices, test_indices = \
            split_indices(indices=indices, splits=adjusted_ratios, random_seed=0)
        train_indices += all_class_subset1
        val_indices += all_class_subset2
        test_indices += all_class_subset3

        train_set = MIBISubsetHypergraph(
            dataset=dataset,
            subset_indices=train_indices)
        val_set = MIBISubsetHypergraph(
            dataset=dataset,
            subset_indices=val_indices)
        test_set = MIBISubsetHypergraph(
            dataset=dataset,
            subset_indices=test_indices)

    min_batch_per_epoch = 5
    desired_len = args.desired_batch_size * min_batch_per_epoch
    if len(train_set) < desired_len:
        train_set = ExtendedDataset(dataset=train_set, desired_len=desired_len)

    train_loader = DataLoader(train_set, batch_size=args.batch_size, num_workers=args.num_workers, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=args.batch_size, num_workers=args.num_workers, shuffle=False)
    test_loader = DataLoader(test_set, batch_size=args.batch_size, num_workers=args.num_workers, shuffle=False)

    return train_loader, val_loader, test_loader, dataset.num_classes

In [4]:
from argparse import Namespace

args = Namespace(
    dataset='mibi',
    data_folder='../data/MIBI/patchified_all_genes',
    train_val_test_ratio='6:2:2',
    desired_batch_size=16,
    batch_size=1,
    k_hop=1,
    num_workers=4,
    max_epochs=50,
    max_training_iters=512,
    max_validation_iters=256,
    learning_rate=1e-2,
    random_seed=1,
)

# Access with dot notation
print(args.dataset)  # 'MIBI'

mibi


In [5]:
dataset = MIBIDataset(data_folder=args.data_folder, k_hop=args.k_hop)
dataset

In [6]:
# Load the data.
train_loader, val_loader, test_loader, num_classes = prepare_dataloaders(args)

In [7]:
dataset = MIBIDataset(data_folder=args.data_folder, k_hop=args.k_hop)

ratios = [float(c) for c in args.train_val_test_ratio.split(':')]
ratios = tuple([c / sum(ratios) for c in ratios])
indices = list(range(len(dataset)))

# NOTE: This is a hack to make sure all sets have all classes.
all_class_subset1 = [0, 1, 4, 6]
all_class_subset2 = [7, 8, 10, 11]
all_class_subset3 = [12, 13, 14, 15]
indices = list(set(indices) - set(all_class_subset1 + all_class_subset2 + all_class_subset3))
adjusted_ratios = len(dataset) * np.array(ratios) - np.array([4, 4, 4])
adjusted_ratios = tuple([c / sum(adjusted_ratios) for c in adjusted_ratios])
train_indices, val_indices, test_indices = \
    split_indices(indices=indices, splits=adjusted_ratios, random_seed=0)
train_indices += all_class_subset1
val_indices += all_class_subset2
test_indices += all_class_subset3

In [8]:
dataset = MIBIDataset(data_folder=args.data_folder, k_hop=args.k_hop)

In [9]:
train_set = MIBISubsetHypergraph(
    dataset=dataset,
    subset_indices=train_indices)

In [10]:
from models.hypergraph_scattering import HypergraphScatteringNet
from utils.seed import seed_everything
from utils.log_utils import log
from utils.data_utils import split_dataset, split_indices
from utils.scheduler import LinearWarmupCosineAnnealingLR
from dataset.placenta import PlacentaDatasetHypergraph
from dataset.mibi import MIBIDataset, MIBISubsetHypergraph
from dataset.extend import ExtendedDataset
import torch

log_file = os.path.join('results', args.dataset, 'log.txt')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
log(f'Using device: {device}', filepath=log_file, to_console=True)


Using device: cuda


In [11]:
log(f'Train set: {len(train_loader.dataset)}, Val set: {len(val_loader.dataset)}, Test set: {len(test_loader.dataset)}', filepath=log_file, to_console=True)

model = HypergraphScatteringNet(
    in_channels=64,
    hidden_channels=64,
    out_channels=num_classes,
    num_features=29,
    trainable_laziness=False,
    trainable_scales=True,
    activation=None,  # just get one layer of wavelet transform
    fixed_weights=True,
    layout=['hsm'],
    normalize='right',
    pooling='attention',
    scale_list=[0,1,2,4]
)
model.to(device)

# Check model parameters
total_params = 0
for param in model.parameters():
    total_params += param.numel() * param.element_size()
log(f"Parameters: {total_params/1e3:.2f}KB", filepath=log_file)

# Set up training tools.
optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate)
scheduler = LinearWarmupCosineAnnealingLR(
    optimizer,
    warmup_epochs=min(10, args.max_epochs),
    warmup_start_lr=args.learning_rate * 1e-2,
    max_epochs=args.max_epochs)
loss_fn = torch.nn.CrossEntropyLoss()

# Log the config.
config_str = 'Config: \n'
for key in vars(args).keys():
    config_str += '%s: %s\n' % (key, vars(args)[key])
config_str += '\nTraining History:'
log(config_str, filepath=log_file, to_console=True)

log(f'[HypergraphScattering] Training begins.', filepath=log_file)
best_val_auroc = 0
best_val_accuracy = 0

Train set: 3610, Val set: 1050, Test set: 1070
Parameters: 4.85KB
Config: 
dataset: mibi
data_folder: ../data/MIBI/patchified_all_genes
train_val_test_ratio: 6:2:2
desired_batch_size: 16
batch_size: 1
k_hop: 1
num_workers: 4
max_epochs: 50
max_training_iters: 512
max_validation_iters: 256
learning_rate: 0.01
random_seed: 1

Training History:
[HypergraphScattering] Training begins.


In [12]:
from tqdm import tqdm
from sklearn.metrics import roc_auc_score, accuracy_score

def train_epoch(model, train_loader, optimizer, loss_fn, device, max_iter, num_classes):
    train_loss = 0
    y_true_arr, y_pred_arr = None, None
    optimizer.zero_grad()
    batch_per_backprop = int(args.desired_batch_size / args.batch_size)

    for iter_idx, data_item in enumerate(tqdm(train_loader)):
        if max_iter is not None and iter_idx > max_iter:
            break

        data_item = data_item.to(device)
        y_true = data_item.y.long()
        y_pred = model(
            x=data_item.x,
            hyperedge_index=data_item.edge_index,
            hyperedge_attr=data_item.edge_attr,
            batch=data_item.batch)

        loss = loss_fn(y_pred, y_true)

        loss_ = loss / batch_per_backprop
        loss_.backward()

        train_loss += loss.mean().item()

        # Simulate bigger batch size by batched optimizer update.
        if iter_idx % batch_per_backprop == batch_per_backprop - 1:
            optimizer.step()
            optimizer.zero_grad()

        y_true_np = y_true.detach().cpu().numpy()                        # shape: (batch size, 1)
        y_pred_np = torch.softmax(y_pred, dim=1).detach().cpu().numpy()  # shape: (batch size, num classes)
        if y_true_arr is None:
            y_true_arr = y_true_np
            y_pred_arr = y_pred_np
        else:
            y_true_arr = np.hstack((y_true_arr, y_true_np))
            y_pred_arr = np.vstack((y_pred_arr, y_pred_np))

    train_loss /= min(max_iter, len(train_loader))
    accuracy = accuracy_score(y_true_arr, np.argmax(y_pred_arr, axis=1))
    auroc = roc_auc_score(y_true_arr, y_pred_arr, multi_class='ovo', average='macro', labels=np.arange(num_classes))
    return model, train_loss, accuracy, auroc


In [13]:
@torch.no_grad()
def val_epoch(model, val_loader, loss_fn, device, max_iter, num_classes):
    val_loss = 0
    y_true_arr, y_pred_arr = None, None

    for iter_idx, data_item in enumerate(val_loader):
        if max_iter is not None and iter_idx > max_iter:
            break

        data_item = data_item.to(device)
        y_true = data_item.y.long()
        y_pred = model(
            x=data_item.x,
            hyperedge_index=data_item.edge_index,
            hyperedge_attr=data_item.edge_attr,
            batch=data_item.batch)
        loss = loss_fn(y_pred, y_true)

        val_loss += loss.mean().item()

        y_true_np = y_true.detach().cpu().numpy()                        # shape: (batch size, 1)
        y_pred_np = torch.softmax(y_pred, dim=1).detach().cpu().numpy()  # shape: (batch size, num classes)
        if y_true_arr is None:
            y_true_arr = y_true_np
            y_pred_arr = y_pred_np
        else:
            y_true_arr = np.hstack((y_true_arr, y_true_np))
            y_pred_arr = np.vstack((y_pred_arr, y_pred_np))

    val_loss /= min(max_iter, len(val_loader))
    accuracy = accuracy_score(y_true_arr, np.argmax(y_pred_arr, axis=1))
    # Check for invalid predictions
    print(y_pred_arr)
    print(np.arange(num_classes))
    print(f"y_pred has NaN: {np.isnan(y_pred_arr).any()}")
    print(f"y_pred has inf: {np.isinf(y_pred_arr).any()}")
    print(f"y_pred range: [{y_pred_arr.min():.3f}, {y_pred_arr.max():.3f}]")
    auroc = roc_auc_score(y_true_arr, y_pred_arr, multi_class='ovo', average='macro', labels=np.arange(num_classes))
    return model, val_loss, accuracy, auroc

In [16]:
model_save_path = os.path.join('results','mibi','model.pt')

In [18]:
for epoch_idx in tqdm(range(args.max_epochs)):
    model.train()
    model, train_loss, train_accuracy, train_auroc = train_epoch(model, train_loader, optimizer, loss_fn, device, args.max_training_iters, num_classes)
    scheduler.step()
    log_lr = optimizer.param_groups[0]['lr']
    log(f'Epoch {epoch_idx + 1}/{args.max_epochs}: (LR={log_lr}) Training Loss {train_loss:.3f}, ACC {train_accuracy:.3f}, macro AUROC {train_auroc:.3f}.',
        filepath=log_file)

    model.eval()
    model, val_loss, val_accuracy, val_auroc = val_epoch(model, val_loader, loss_fn, device, args.max_validation_iters, num_classes)
    log(f'Validation Loss {val_loss:.3f}, ACC {val_accuracy:.3f}, macro AUROC {val_auroc:.3f}.',
        filepath=log_file)
    # if val_auroc > best_val_auroc:
    if val_accuracy > best_val_accuracy:
        best_val_accuracy = val_accuracy
        torch.save(model.state_dict(), model_save_path)
        log('Model weights successfully saved.', filepath=log_file)

 14%|█▍        | 513/3610 [00:55<05:36,  9.20it/s]

Epoch 1/50: (LR=0.005600000000000001) Training Loss 1.258, ACC 0.441, macro AUROC 0.676.



  2%|▏         | 1/50 [01:22<1:07:33, 82.73s/it]

[[0.2342301  0.6399408  0.09494728 0.03088188]
 [0.37279084 0.47620937 0.11445735 0.03654244]
 [0.58260626 0.12779959 0.20466143 0.08493274]
 ...
 [0.5047646  0.27191922 0.17846957 0.04484661]
 [0.52934676 0.22975011 0.18034469 0.06055846]
 [0.2886032  0.36229628 0.23099428 0.11810622]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.003, 0.953]
Validation Loss 1.532, ACC 0.331, macro AUROC 0.396.


 14%|█▍        | 513/3610 [00:53<05:24,  9.55it/s]

Epoch 2/50: (LR=0.006700000000000001) Training Loss 1.132, ACC 0.497, macro AUROC 0.737.



  4%|▍         | 2/50 [02:44<1:05:53, 82.37s/it]

[[0.43515268 0.3110016  0.18816541 0.06568028]
 [0.5245055  0.22469391 0.18790141 0.06289916]
 [0.6319408  0.11660721 0.17225076 0.07920128]
 ...
 [0.5867259  0.10723642 0.22787578 0.07816195]
 [0.635724   0.09264026 0.19569564 0.07594013]
 [0.34759474 0.20243523 0.28546247 0.16450752]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.014, 0.814]
Validation Loss 1.569, ACC 0.222, macro AUROC 0.432.


 14%|█▍        | 513/3610 [00:59<06:00,  8.58it/s]

Epoch 3/50: (LR=0.007800000000000001) Training Loss 1.012, ACC 0.591, macro AUROC 0.808.



  6%|▌         | 3/50 [04:13<1:06:47, 85.26s/it]

[[0.06411607 0.87151396 0.0597254  0.00464452]
 [0.22450869 0.6663293  0.10281979 0.00634218]
 [0.71013606 0.15050147 0.12927194 0.01009048]
 ...
 [0.61539924 0.2262299  0.14321768 0.01515314]
 [0.49903852 0.30274084 0.17062488 0.02759573]
 [0.17394382 0.37191367 0.36022985 0.0939127 ]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 0.987]
Validation Loss 1.514, ACC 0.315, macro AUROC 0.389.


 14%|█▍        | 513/3610 [00:58<05:54,  8.74it/s]

Epoch 4/50: (LR=0.008900000000000002) Training Loss 0.988, ACC 0.565, macro AUROC 0.805.



  8%|▊         | 4/50 [05:39<1:05:29, 85.43s/it]

[[0.0129577  0.63147134 0.3221     0.03347097]
 [0.01822121 0.61330104 0.33286682 0.03561094]
 [0.3506318  0.24653608 0.34556195 0.05727015]
 ...
 [0.3855643  0.27683577 0.28313327 0.05446676]
 [0.4597157  0.26005784 0.24172366 0.0385028 ]
 [0.20911732 0.36994275 0.37843916 0.04250078]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 0.933]
Validation Loss 1.605, ACC 0.288, macro AUROC 0.290.


 14%|█▍        | 513/3610 [00:57<05:48,  8.90it/s]

Epoch 5/50: (LR=0.010000000000000002) Training Loss 0.978, ACC 0.558, macro AUROC 0.815.



 10%|█         | 5/50 [07:09<1:05:15, 87.00s/it]

[[0.07129525 0.5746086  0.22110184 0.13299432]
 [0.09138919 0.50598496 0.29228964 0.1103362 ]
 [0.2799997  0.33998546 0.2713319  0.1086829 ]
 ...
 [0.40014017 0.30850554 0.25221613 0.03913818]
 [0.46924824 0.30153492 0.18937573 0.03984116]
 [0.17244005 0.55963975 0.14330669 0.12461349]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 0.952]
Validation Loss 1.815, ACC 0.233, macro AUROC 0.320.


 14%|█▍        | 513/3610 [00:58<05:51,  8.80it/s]

Epoch 6/50: (LR=0.01) Training Loss 0.898, ACC 0.622, macro AUROC 0.851.



 12%|█▏        | 6/50 [08:34<1:03:21, 86.40s/it]

[[0.04312415 0.45687634 0.31859732 0.18140219]
 [0.03705096 0.28456333 0.60302985 0.07535584]
 [0.36574018 0.15713063 0.41817024 0.05895897]
 ...
 [0.97964925 0.00101373 0.01825494 0.00108211]
 [0.961477   0.00446186 0.03025712 0.00380392]
 [0.515809   0.12695903 0.2774579  0.07977407]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.530, ACC 0.093, macro AUROC 0.404.


 14%|█▍        | 513/3610 [00:56<05:43,  9.01it/s]

Epoch 7/50: (LR=0.00998458666866564) Training Loss 0.836, ACC 0.690, macro AUROC 0.880.



 14%|█▍        | 7/50 [09:59<1:01:32, 85.87s/it]

[[0.02197916 0.8199193  0.09407907 0.06402248]
 [0.02837238 0.64570034 0.28955072 0.03637656]
 [0.08980198 0.22606304 0.6291679  0.05496705]
 ...
 [0.27564278 0.26030952 0.45209795 0.01194967]
 [0.30243078 0.21380004 0.4710981  0.01267112]
 [0.06417218 0.56606966 0.2946598  0.07509832]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 0.997]
Validation Loss 1.728, ACC 0.354, macro AUROC 0.430.


 14%|█▍        | 513/3610 [00:58<05:51,  8.82it/s]

Epoch 8/50: (LR=0.009938441702975689) Training Loss 0.733, ACC 0.737, macro AUROC 0.910.



 16%|█▌        | 8/50 [11:24<1:00:06, 85.86s/it]

[[0.05101233 0.6070698  0.08803724 0.25388062]
 [0.0633117  0.5804221  0.18644229 0.16982393]
 [0.30781248 0.23165034 0.14317739 0.3173598 ]
 ...
 [0.17017876 0.791745   0.02238215 0.01569408]
 [0.38649115 0.5771978  0.02081289 0.01549814]
 [0.07567444 0.61118865 0.15368494 0.15945195]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 0.998]
Validation Loss 2.424, ACC 0.148, macro AUROC 0.355.


 14%|█▍        | 513/3610 [00:58<05:55,  8.71it/s]

Epoch 9/50: (LR=0.009861849601988383) Training Loss 0.709, ACC 0.721, macro AUROC 0.910.



 18%|█▊        | 9/50 [12:52<58:58, 86.29s/it]  

[[0.16126403 0.37090474 0.2661806  0.2016506 ]
 [0.22249627 0.25002727 0.46820295 0.05927352]
 [0.38706562 0.10554372 0.4657687  0.04162199]
 ...
 [0.72458524 0.19542594 0.07635155 0.00363725]
 [0.86569405 0.07048231 0.06186594 0.00195771]
 [0.04909163 0.76359963 0.14587896 0.04142974]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.719, ACC 0.109, macro AUROC 0.319.


 14%|█▍        | 513/3610 [00:53<05:21,  9.64it/s]

Epoch 10/50: (LR=0.009755282581475769) Training Loss 0.681, ACC 0.741, macro AUROC 0.916.



 20%|██        | 10/50 [14:13<56:26, 84.67s/it]

[[0.14751275 0.5415769  0.17505695 0.13585338]
 [0.20253281 0.35748369 0.39779678 0.04218673]
 [0.28331307 0.21292208 0.4693253  0.03443948]
 ...
 [0.61813885 0.33309993 0.04332262 0.00543865]
 [0.6271103  0.31012058 0.05717887 0.00559027]
 [0.1124806  0.55951536 0.29608026 0.03192382]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 0.982]
Validation Loss 1.937, ACC 0.253, macro AUROC 0.323.


 14%|█▍        | 513/3610 [00:54<05:28,  9.44it/s]

Epoch 11/50: (LR=0.009619397662556435) Training Loss 0.576, ACC 0.766, macro AUROC 0.939.



 22%|██▏       | 11/50 [15:38<55:12, 84.93s/it]

[[0.0134698  0.917819   0.01484145 0.05386977]
 [0.06499313 0.11407761 0.81245285 0.00847638]
 [0.08379366 0.0425843  0.8699106  0.00371142]
 ...
 [0.42689037 0.45803276 0.11396183 0.00111502]
 [0.25075972 0.5853502  0.16230293 0.00158711]
 [0.01548676 0.81296444 0.16529526 0.0062535 ]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.560, ACC 0.210, macro AUROC 0.356.


 14%|█▍        | 513/3610 [00:58<05:52,  8.78it/s]

Epoch 12/50: (LR=0.00945503262094184) Training Loss 0.487, ACC 0.823, macro AUROC 0.957.



 24%|██▍       | 12/50 [17:05<54:03, 85.36s/it]

[[4.5754779e-03 8.8149416e-01 4.0744152e-04 1.1352294e-01]
 [5.1282007e-01 2.1643122e-01 8.1703253e-02 1.8904549e-01]
 [7.4916005e-01 7.1007147e-02 1.1272157e-01 6.7111246e-02]
 ...
 [9.8469770e-01 1.3923361e-03 1.2941817e-02 9.6818863e-04]
 [9.1107911e-01 1.9303948e-02 6.1032534e-02 8.5844230e-03]
 [5.4529816e-01 5.6287151e-02 3.3885625e-01 5.9558425e-02]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.823, ACC 0.109, macro AUROC 0.536.


 14%|█▍        | 513/3610 [00:57<05:44,  8.98it/s]

Epoch 13/50: (LR=0.009263200821770462) Training Loss 0.413, ACC 0.852, macro AUROC 0.967.



 26%|██▌       | 13/50 [18:29<52:28, 85.09s/it]

[[3.5398785e-02 8.8149059e-01 6.7342119e-03 7.6376401e-02]
 [6.7404866e-01 7.2793260e-02 2.5099593e-01 2.1621115e-03]
 [7.8727019e-01 2.5731545e-02 1.8578346e-01 1.2148466e-03]
 ...
 [9.6024424e-01 3.8010061e-02 1.7342920e-03 1.1425338e-05]
 [4.9192327e-01 5.0204688e-01 5.9816479e-03 4.8262635e-05]
 [2.9321522e-01 6.8260747e-01 2.3781268e-02 3.9600607e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.289, ACC 0.233, macro AUROC 0.439.


 14%|█▍        | 513/3610 [00:58<05:53,  8.75it/s]

Epoch 14/50: (LR=0.009045084971874739) Training Loss 0.377, ACC 0.850, macro AUROC 0.971.



 28%|██▊       | 14/50 [19:56<51:26, 85.73s/it]

[[0.03725493 0.5350605  0.01502373 0.41266084]
 [0.5942749  0.09821445 0.23003347 0.0774772 ]
 [0.76926595 0.03328013 0.14454158 0.05291236]
 ...
 [0.9483377  0.03207918 0.01666016 0.00292302]
 [0.40145776 0.48135725 0.08849441 0.02869056]
 [0.04689754 0.66097736 0.08352213 0.2086029 ]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.791, ACC 0.128, macro AUROC 0.489.


 14%|█▍        | 513/3610 [00:56<05:38,  9.14it/s]

Epoch 15/50: (LR=0.008802029828000156) Training Loss 0.385, ACC 0.867, macro AUROC 0.971.



 30%|███       | 15/50 [21:20<49:40, 85.15s/it]

[[5.83048768e-06 9.94981229e-01 6.18282854e-07 5.01233246e-03]
 [3.21471155e-01 4.35831666e-01 3.12701575e-02 2.11427063e-01]
 [7.84752786e-01 7.93024451e-02 7.69859776e-02 5.89587763e-02]
 ...
 [9.38375831e-01 3.22694853e-02 2.93421503e-02 1.25699553e-05]
 [8.67186606e-01 1.14796154e-01 1.78281628e-02 1.89088605e-04]
 [7.20391512e-01 2.23174304e-01 5.34361452e-02 2.99803633e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.600, ACC 0.187, macro AUROC 0.469.


 14%|█▍        | 513/3610 [00:58<05:54,  8.74it/s]

Epoch 16/50: (LR=0.008535533905932738) Training Loss 0.377, ACC 0.862, macro AUROC 0.972.



 32%|███▏      | 16/50 [22:50<49:04, 86.61s/it]

[[3.8214228e-03 9.2143917e-01 3.5230024e-04 7.4387118e-02]
 [3.6312979e-01 5.7367887e-02 5.7084507e-01 8.6572058e-03]
 [2.7261728e-01 1.0476295e-02 7.1568084e-01 1.2255887e-03]
 ...
 [9.9739206e-01 2.4926371e-04 2.3580804e-03 5.6212173e-07]
 [9.8844689e-01 2.3309789e-03 9.2079537e-03 1.4100385e-05]
 [9.5850277e-01 6.9204834e-03 3.4197234e-02 3.7953720e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.361, ACC 0.082, macro AUROC 0.544.


 14%|█▍        | 513/3610 [00:54<05:31,  9.34it/s]

Epoch 17/50: (LR=0.00824724024165092) Training Loss 0.357, ACC 0.852, macro AUROC 0.978.



 34%|███▍      | 17/50 [24:13<47:02, 85.53s/it]

[[6.1932728e-03 7.8267139e-01 4.0335578e-04 2.1073192e-01]
 [4.0785468e-01 2.5275734e-01 2.7785778e-01 6.1530218e-02]
 [4.9080583e-01 9.2462137e-02 4.0034097e-01 1.6390998e-02]
 ...
 [9.4945973e-01 9.4825076e-03 4.1015934e-02 4.1823761e-05]
 [8.5872537e-01 1.0784885e-01 3.2965917e-02 4.5996768e-04]
 [4.8199221e-01 4.0841830e-01 1.0626512e-01 3.3243569e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.787, ACC 0.237, macro AUROC 0.575.


 14%|█▍        | 513/3610 [00:59<05:59,  8.61it/s]

Epoch 18/50: (LR=0.007938926261462366) Training Loss 0.268, ACC 0.897, macro AUROC 0.986.



 36%|███▌      | 18/50 [25:42<46:08, 86.52s/it]

[[2.08040888e-06 9.93886411e-01 1.09682130e-08 6.11147704e-03]
 [2.04002380e-01 4.02328283e-01 6.37231069e-03 3.87297064e-01]
 [8.66707265e-01 6.03686348e-02 3.42506208e-02 3.86734456e-02]
 ...
 [9.92548287e-01 4.42216080e-03 3.02763213e-03 2.01323928e-06]
 [6.52046680e-01 3.13276947e-01 3.42930891e-02 3.83297069e-04]
 [1.04910955e-01 6.67477190e-01 2.26202890e-01 1.40895299e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.863, ACC 0.175, macro AUROC 0.428.


 14%|█▍        | 513/3610 [00:57<05:46,  8.94it/s]

Epoch 19/50: (LR=0.0076124928235797445) Training Loss 0.256, ACC 0.897, macro AUROC 0.988.



 38%|███▊      | 19/50 [27:06<44:20, 85.82s/it]

[[1.07092819e-04 9.81651545e-01 4.14896385e-06 1.82371978e-02]
 [1.30212769e-01 4.63484883e-01 3.28527778e-01 7.77745843e-02]
 [2.90810257e-01 1.64193228e-01 5.19246519e-01 2.57500187e-02]
 ...
 [8.08697701e-01 1.20202094e-01 7.10867792e-02 1.35066266e-05]
 [8.33099559e-02 8.26399386e-01 8.99958760e-02 2.94762780e-04]
 [1.21343462e-02 9.32588160e-01 5.45835644e-02 6.93909999e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.292, ACC 0.136, macro AUROC 0.511.


 14%|█▍        | 513/3610 [00:54<05:30,  9.38it/s]

Epoch 20/50: (LR=0.007269952498697735) Training Loss 0.207, ACC 0.920, macro AUROC 0.990.



 40%|████      | 20/50 [28:29<42:32, 85.07s/it]

[[6.0642390e-07 9.9943811e-01 1.8994418e-08 5.6129281e-04]
 [9.0572489e-03 9.8756427e-01 2.5959008e-03 7.8258809e-04]
 [1.4433064e-01 7.7995181e-01 7.5022720e-02 6.9481577e-04]
 ...
 [9.9258786e-01 6.0336441e-03 1.3784372e-03 6.4970109e-08]
 [8.9285791e-01 1.0198478e-01 5.1562237e-03 1.1181774e-06]
 [2.2771059e-01 7.2319353e-01 4.8923608e-02 1.7226522e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.048, ACC 0.202, macro AUROC 0.509.


 14%|█▍        | 513/3610 [00:54<05:31,  9.34it/s]

Epoch 21/50: (LR=0.0069134171618254504) Training Loss 0.257, ACC 0.910, macro AUROC 0.986.



 42%|████▏     | 21/50 [29:52<40:49, 84.46s/it]

[[5.7900928e-05 9.9420482e-01 7.1909039e-06 5.7300744e-03]
 [9.6809514e-02 6.3577920e-01 1.0805829e-01 1.5935303e-01]
 [3.5296363e-01 1.2687744e-01 4.3946600e-01 8.0692932e-02]
 ...
 [9.0008825e-01 7.4363579e-03 9.2455938e-02 1.9475017e-05]
 [3.7525132e-01 2.7462879e-01 3.4893754e-01 1.1823417e-03]
 [3.5163164e-02 5.9768033e-01 3.6341673e-01 3.7398718e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.613, ACC 0.163, macro AUROC 0.536.


 14%|█▍        | 513/3610 [00:57<05:46,  8.95it/s]

Epoch 22/50: (LR=0.006545084971874739) Training Loss 0.229, ACC 0.924, macro AUROC 0.991.



 44%|████▍     | 22/50 [31:19<39:47, 85.25s/it]

[[1.7974309e-04 9.6046001e-01 6.7755806e-05 3.9292391e-02]
 [2.7936029e-01 2.7641612e-01 2.8220737e-01 1.6201623e-01]
 [3.7821674e-01 5.8088869e-02 5.2235937e-01 4.1335065e-02]
 ...
 [9.0447837e-01 5.7730041e-03 8.9459009e-02 2.8962491e-04]
 [3.6028141e-01 1.4470917e-01 4.8804057e-01 6.9688614e-03]
 [4.9890690e-02 1.5214238e-01 7.5850475e-01 3.9462231e-02]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.001, ACC 0.230, macro AUROC 0.524.


 14%|█▍        | 513/3610 [00:53<05:25,  9.51it/s]

Epoch 23/50: (LR=0.006167226819279529) Training Loss 0.233, ACC 0.912, macro AUROC 0.989.



 46%|████▌     | 23/50 [32:41<37:52, 84.16s/it]

[[1.09925715e-03 9.08087611e-01 2.90994240e-06 9.08102766e-02]
 [1.10700652e-01 1.03061095e-01 7.71228671e-01 1.50095727e-02]
 [5.94711713e-02 5.97110018e-03 9.33867216e-01 6.90480345e-04]
 ...
 [9.75103736e-01 7.56971480e-04 2.41389703e-02 2.93354674e-07]
 [8.54843795e-01 5.39788231e-02 9.11205634e-02 5.67695060e-05]
 [6.01456463e-01 2.12476134e-01 1.85374752e-01 6.92610571e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.394, ACC 0.140, macro AUROC 0.613.


 14%|█▍        | 513/3610 [00:58<05:53,  8.77it/s]

Epoch 24/50: (LR=0.005782172325201156) Training Loss 0.176, ACC 0.936, macro AUROC 0.994.



 48%|████▊     | 24/50 [34:07<36:44, 84.80s/it]

[[5.2066393e-06 9.9833715e-01 1.2435878e-09 1.6575569e-03]
 [1.6796724e-01 6.0803777e-01 5.1263254e-03 2.1886869e-01]
 [6.8409896e-01 1.3696714e-01 1.1463351e-01 6.4300425e-02]
 ...
 [9.4927204e-01 4.8615630e-03 4.5865059e-02 1.3225127e-06]
 [3.5146698e-01 2.3963819e-01 4.0834785e-01 5.4703513e-04]
 [3.2887928e-02 3.2024190e-01 6.4559031e-01 1.2798989e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.579, ACC 0.226, macro AUROC 0.596.


 14%|█▍        | 513/3610 [00:58<05:51,  8.82it/s]

Epoch 25/50: (LR=0.005392295478639226) Training Loss 0.219, ACC 0.910, macro AUROC 0.991.



 50%|█████     | 25/50 [35:33<35:25, 85.03s/it]

[[4.4109925e-06 9.9933594e-01 3.4470244e-09 6.5965077e-04]
 [1.1599338e-01 6.6658729e-01 2.1805223e-02 1.9561405e-01]
 [4.2434120e-01 1.3124287e-01 3.8877189e-01 5.5643976e-02]
 ...
 [7.2141927e-01 2.5378838e-03 2.7603155e-01 1.1239077e-05]
 [5.8928365e-01 1.4995836e-01 2.5947937e-01 1.2785828e-03]
 [5.2857286e-01 2.7214742e-01 1.9742215e-01 1.8575145e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.724, ACC 0.241, macro AUROC 0.714.


 14%|█▍        | 513/3610 [00:58<05:55,  8.71it/s]

Epoch 26/50: (LR=0.005000000000000001) Training Loss 0.162, ACC 0.942, macro AUROC 0.995.



 52%|█████▏    | 26/50 [36:58<34:04, 85.17s/it]

[[1.83595548e-05 9.80439126e-01 1.02644179e-07 1.95423812e-02]
 [2.24297289e-02 2.75798023e-01 3.46137322e-02 6.67158484e-01]
 [1.02038816e-01 1.48748696e-01 3.55377525e-01 3.93834978e-01]
 ...
 [5.47267973e-01 1.96346156e-02 4.33003992e-01 9.33709962e-05]
 [6.44901544e-02 3.32180053e-01 5.99003255e-01 4.32648975e-03]
 [8.59204028e-03 3.50142866e-01 6.35769486e-01 5.49558923e-03]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.695, ACC 0.237, macro AUROC 0.656.


 14%|█▍        | 513/3610 [00:56<05:39,  9.13it/s]

Epoch 27/50: (LR=0.004607704521360776) Training Loss 0.134, ACC 0.951, macro AUROC 0.997.



 54%|█████▍    | 27/50 [38:25<32:45, 85.47s/it]

[[6.66401002e-06 9.85115111e-01 1.24659778e-07 1.48780718e-02]
 [1.57431625e-02 2.26116449e-01 6.90328777e-01 6.78116009e-02]
 [1.48566859e-02 1.23834945e-02 9.67307985e-01 5.45183849e-03]
 ...
 [6.72193170e-01 5.89259760e-03 3.21913302e-01 8.87624083e-07]
 [1.11648165e-01 3.76389086e-01 5.11813045e-01 1.49634099e-04]
 [2.26936471e-02 3.84427339e-01 5.92692912e-01 1.86154270e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.213, ACC 0.206, macro AUROC 0.588.


 14%|█▍        | 513/3610 [00:57<05:44,  8.99it/s]

Epoch 28/50: (LR=0.004217827674798847) Training Loss 0.155, ACC 0.943, macro AUROC 0.994.



 56%|█████▌    | 28/50 [39:55<31:49, 86.82s/it]

[[1.6046260e-05 9.6598089e-01 1.0525261e-07 3.4002971e-02]
 [3.0744201e-01 2.1396805e-01 4.1402158e-01 6.4568371e-02]
 [4.2616522e-01 5.7181582e-02 5.0742507e-01 9.2280963e-03]
 ...
 [7.6478618e-01 1.1812599e-03 2.3403239e-01 1.2364133e-07]
 [2.3242106e-01 2.3377104e-01 5.3378797e-01 1.9912859e-05]
 [8.5075088e-02 6.4633822e-01 2.6852462e-01 6.2091196e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.004, ACC 0.206, macro AUROC 0.561.


 14%|█▍        | 513/3610 [00:57<05:45,  8.97it/s]

Epoch 29/50: (LR=0.0038327731807204736) Training Loss 0.110, ACC 0.965, macro AUROC 0.998.



 58%|█████▊    | 29/50 [41:21<30:18, 86.58s/it]

[[9.4083966e-08 9.9926108e-01 1.3052165e-09 7.3873636e-04]
 [8.5762240e-02 7.6558679e-01 7.8262866e-02 7.0388116e-02]
 [3.8189691e-01 7.6885015e-02 5.2721095e-01 1.4007178e-02]
 ...
 [9.7800314e-01 6.3556293e-04 2.1361373e-02 9.4373487e-09]
 [4.9808618e-01 1.3570477e-01 3.6619478e-01 1.4208970e-05]
 [2.1637121e-02 2.3654449e-01 7.4176443e-01 5.3998378e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.508, ACC 0.241, macro AUROC 0.577.


 14%|█▍        | 513/3610 [00:55<05:34,  9.25it/s]

Epoch 30/50: (LR=0.003454915028125263) Training Loss 0.144, ACC 0.945, macro AUROC 0.995.



 60%|██████    | 30/50 [42:43<28:25, 85.28s/it]

[[3.89083823e-08 9.99616146e-01 1.42272971e-10 3.83766892e-04]
 [3.28470580e-03 6.83624983e-01 4.57994267e-03 3.08510453e-01]
 [1.20911799e-01 2.84233570e-01 3.78613025e-01 2.16241583e-01]
 ...
 [7.92859137e-01 2.95998324e-02 1.77538574e-01 2.45544720e-06]
 [8.68235305e-02 6.75434053e-01 2.37622917e-01 1.19505145e-04]
 [8.05333070e-03 6.69538975e-01 3.22108954e-01 2.98746221e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.082, ACC 0.253, macro AUROC 0.607.


 14%|█▍        | 513/3610 [00:55<05:37,  9.17it/s]

Epoch 31/50: (LR=0.0030865828381745515) Training Loss 0.130, ACC 0.955, macro AUROC 0.997.



 62%|██████▏   | 31/50 [44:06<26:46, 84.55s/it]

[[6.27551060e-08 9.99826968e-01 7.64654062e-10 1.72902903e-04]
 [1.94589999e-02 6.79180682e-01 1.16360456e-01 1.84999824e-01]
 [7.53324553e-02 4.84642200e-02 8.51470411e-01 2.47329511e-02]
 ...
 [8.75590801e-01 4.39342251e-03 1.20015673e-01 1.12912289e-07]
 [4.11806732e-01 2.97118366e-01 2.90979177e-01 9.57254597e-05]
 [8.35589170e-02 4.42271769e-01 4.73768264e-01 4.01085563e-04]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.779, ACC 0.202, macro AUROC 0.584.


 14%|█▍        | 513/3610 [00:57<05:49,  8.85it/s]

Epoch 32/50: (LR=0.0027300475013022664) Training Loss 0.129, ACC 0.953, macro AUROC 0.997.



 64%|██████▍   | 32/50 [45:31<25:27, 84.88s/it]

[[3.50393172e-08 9.99859571e-01 5.84720661e-10 1.40413293e-04]
 [1.25674130e-02 9.38696921e-01 2.49769874e-02 2.37586945e-02]
 [1.04895018e-01 1.85051471e-01 7.01107621e-01 8.94593913e-03]
 ...
 [8.60061109e-01 1.47225065e-02 1.25216261e-01 8.18665740e-08]
 [1.40742287e-01 4.92291927e-01 3.66946846e-01 1.89600032e-05]
 [9.96316690e-03 6.39217198e-01 3.50772858e-01 4.68291400e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 2.838, ACC 0.292, macro AUROC 0.628.


 14%|█▍        | 513/3610 [00:56<05:43,  9.01it/s]

Epoch 33/50: (LR=0.002387507176420256) Training Loss 0.104, ACC 0.965, macro AUROC 0.998.



 66%|██████▌   | 33/50 [46:55<23:57, 84.56s/it]

[[5.47006493e-07 9.99178231e-01 6.12988726e-09 8.21169815e-04]
 [4.44624901e-01 3.92728180e-01 1.40313834e-01 2.23330371e-02]
 [4.60094959e-01 5.23899049e-02 4.84925449e-01 2.58966372e-03]
 ...
 [9.82981503e-01 3.96789779e-04 1.66216530e-02 1.15702881e-09]
 [5.23235798e-01 1.12973616e-01 3.63787770e-01 2.84945759e-06]
 [3.57333869e-02 2.67460287e-01 6.96793497e-01 1.27789581e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.631, ACC 0.233, macro AUROC 0.652.


 14%|█▍        | 513/3610 [00:56<05:42,  9.04it/s]

Epoch 34/50: (LR=0.002061073738537635) Training Loss 0.092, ACC 0.971, macro AUROC 0.998.



 68%|██████▊   | 34/50 [48:19<22:29, 84.36s/it]

[[6.72311700e-08 9.99557912e-01 5.37284439e-10 4.41917538e-04]
 [2.18803763e-01 6.08836889e-01 1.21017732e-01 5.13415672e-02]
 [3.46996486e-01 4.19122353e-02 6.05751336e-01 5.33993030e-03]
 ...
 [9.85854208e-01 9.74773793e-05 1.40483817e-02 3.77608417e-10]
 [6.25304222e-01 3.16267572e-02 3.43067020e-01 1.93028336e-06]
 [5.01399003e-02 1.05499856e-01 8.44346464e-01 1.38237656e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 3.932, ACC 0.233, macro AUROC 0.662.


 14%|█▍        | 513/3610 [00:54<05:29,  9.40it/s]

Epoch 35/50: (LR=0.0017527597583490825) Training Loss 0.094, ACC 0.967, macro AUROC 0.998.



 70%|███████   | 35/50 [49:43<21:03, 84.25s/it]

[[5.5421573e-08 9.9939060e-01 1.1373465e-10 6.0940778e-04]
 [1.5914743e-01 6.6874909e-01 6.2052663e-02 1.1005085e-01]
 [4.3999749e-01 4.9251728e-02 5.0175452e-01 8.9962892e-03]
 ...
 [9.9717724e-01 6.2300547e-05 2.7604445e-03 1.1018422e-10]
 [8.0156052e-01 3.8125049e-02 1.6031250e-01 1.9101772e-06]
 [4.5933064e-02 1.7170484e-01 7.8233200e-01 3.0179421e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.691, ACC 0.183, macro AUROC 0.634.


 14%|█▍        | 513/3610 [00:59<05:56,  8.69it/s]

Epoch 36/50: (LR=0.0014644660940672629) Training Loss 0.099, ACC 0.967, macro AUROC 0.998.



 72%|███████▏  | 36/50 [51:09<19:46, 84.76s/it]

[[4.77902574e-07 9.98593986e-01 1.43729766e-08 1.40557508e-03]
 [1.49700373e-01 3.07676405e-01 5.28755188e-01 1.38679957e-02]
 [1.01496637e-01 1.51086999e-02 8.82430732e-01 9.63962462e-04]
 ...
 [9.92659390e-01 1.04605017e-04 7.23607233e-03 9.59236787e-11]
 [7.10705936e-01 6.82096332e-02 2.21083105e-01 1.36840026e-06]
 [2.82891989e-02 2.28058830e-01 7.43637562e-01 1.44251335e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.225, ACC 0.206, macro AUROC 0.646.


 14%|█▍        | 513/3610 [00:57<05:46,  8.93it/s]

Epoch 37/50: (LR=0.0011979701719998454) Training Loss 0.076, ACC 0.969, macro AUROC 0.999.



 74%|███████▍  | 37/50 [52:36<18:28, 85.31s/it]

[[8.4294601e-07 9.9720734e-01 9.8233128e-09 2.7918576e-03]
 [3.0264336e-01 1.7454401e-01 4.9720180e-01 2.5610896e-02]
 [2.5983977e-01 2.1133810e-02 7.1760106e-01 1.4253660e-03]
 ...
 [9.9812156e-01 2.0428379e-05 1.8579458e-03 5.3805231e-11]
 [9.0363801e-01 2.5463412e-02 7.0897698e-02 9.3500876e-07]
 [8.0848090e-02 2.4479629e-01 6.7431986e-01 3.5765483e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.920, ACC 0.171, macro AUROC 0.629.


 14%|█▍        | 513/3610 [00:59<05:57,  8.66it/s]

Epoch 38/50: (LR=0.0009549150281252633) Training Loss 0.062, ACC 0.979, macro AUROC 0.999.



 76%|███████▌  | 38/50 [54:02<17:06, 85.57s/it]

[[4.54780036e-07 9.98696983e-01 5.77607873e-09 1.30257057e-03]
 [1.35378659e-01 2.93182135e-01 5.63454092e-01 7.98506383e-03]
 [9.50691178e-02 3.32145095e-02 8.71064425e-01 6.51963230e-04]
 ...
 [9.87731040e-01 2.48000986e-04 1.20210061e-02 7.46394196e-11]
 [5.40279865e-01 2.04297885e-01 2.55421460e-01 7.64774711e-07]
 [1.50973825e-02 4.58426058e-01 5.26470721e-01 5.80492087e-06]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.110, ACC 0.233, macro AUROC 0.604.


 14%|█▍        | 513/3610 [00:55<05:36,  9.20it/s]

Epoch 39/50: (LR=0.0007367991782295391) Training Loss 0.074, ACC 0.979, macro AUROC 0.999.



 78%|███████▊  | 39/50 [55:28<15:43, 85.74s/it]

[[7.2615882e-07 9.9739033e-01 3.3145489e-09 2.6089766e-03]
 [2.7142113e-01 2.4397664e-01 4.6138659e-01 2.3215655e-02]
 [2.1201499e-01 2.6596092e-02 7.6008755e-01 1.3013928e-03]
 ...
 [9.9512535e-01 2.4161258e-05 4.8504588e-03 5.5012706e-11]
 [8.0578446e-01 4.1384686e-02 1.5283015e-01 6.5370813e-07]
 [5.8788165e-02 3.1982586e-01 6.2136722e-01 1.8796089e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.932, ACC 0.187, macro AUROC 0.615.


 14%|█▍        | 513/3610 [00:57<05:45,  8.95it/s]

Epoch 40/50: (LR=0.0005449673790581611) Training Loss 0.072, ACC 0.981, macro AUROC 0.999.



 80%|████████  | 40/50 [56:51<14:10, 85.06s/it]

[[1.5760213e-06 9.9487489e-01 1.1988536e-08 5.1236241e-03]
 [7.5808145e-02 2.2855105e-01 6.8684393e-01 8.7968018e-03]
 [6.1472721e-02 2.5496386e-02 9.1236258e-01 6.6829385e-04]
 ...
 [9.9270296e-01 7.9909056e-05 7.2172130e-03 1.1708223e-10]
 [6.2204063e-01 1.4136609e-01 2.3659171e-01 1.5485075e-06]
 [3.1369749e-02 5.3208882e-01 4.3651056e-01 3.0904524e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.760, ACC 0.183, macro AUROC 0.600.


 14%|█▍        | 513/3610 [00:53<05:25,  9.52it/s]

Epoch 41/50: (LR=0.0003806023374435663) Training Loss 0.069, ACC 0.979, macro AUROC 0.999.



 82%|████████▏ | 41/50 [58:13<12:35, 83.96s/it]

[[6.2108347e-07 9.9643791e-01 4.3473056e-09 3.5615151e-03]
 [4.5850910e-02 3.2941428e-01 6.0580432e-01 1.8930510e-02]
 [4.0503584e-02 3.1698305e-02 9.2667270e-01 1.1255154e-03]
 ...
 [9.7348368e-01 1.2666929e-04 2.6389580e-02 5.3569632e-10]
 [4.1655433e-01 1.2197753e-01 4.6146384e-01 4.1917997e-06]
 [1.4746638e-02 3.2306576e-01 6.6214788e-01 3.9701506e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.471, ACC 0.198, macro AUROC 0.612.


 14%|█▍        | 513/3610 [00:55<05:36,  9.20it/s]

Epoch 42/50: (LR=0.00024471741852423234) Training Loss 0.057, ACC 0.984, macro AUROC 0.999.



 84%|████████▍ | 42/50 [59:35<11:07, 83.39s/it]

[[3.73889463e-07 9.97142375e-01 1.14500487e-09 2.85724620e-03]
 [7.18127936e-02 5.23740709e-01 3.58392447e-01 4.60540652e-02]
 [7.67082572e-02 6.75770938e-02 8.52003276e-01 3.71132791e-03]
 ...
 [9.70973134e-01 1.24016558e-04 2.89028808e-02 1.32841804e-09]
 [4.49368745e-01 1.12561874e-01 4.38061059e-01 8.32594014e-06]
 [2.37554163e-02 3.63388658e-01 6.12792492e-01 6.34661483e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.244, ACC 0.206, macro AUROC 0.635.


 14%|█▍        | 513/3610 [00:56<05:42,  9.04it/s]

Epoch 43/50: (LR=0.00013815039801161723) Training Loss 0.048, ACC 0.986, macro AUROC 0.999.



 86%|████████▌ | 43/50 [1:01:00<09:46, 83.79s/it]

[[3.5311618e-07 9.9691439e-01 9.7418795e-10 3.0852349e-03]
 [8.8407867e-02 5.2336627e-01 3.3661970e-01 5.1606178e-02]
 [9.7224668e-02 6.7939617e-02 8.3088529e-01 3.9504138e-03]
 ...
 [9.7809178e-01 9.3089351e-05 2.1815168e-02 9.5674113e-10]
 [5.1218963e-01 9.8956421e-02 3.8884720e-01 6.7505844e-06]
 [2.8394921e-02 3.4800336e-01 6.2354130e-01 6.0403770e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.337, ACC 0.206, macro AUROC 0.633.


 14%|█▍        | 513/3610 [00:57<05:47,  8.90it/s]

Epoch 44/50: (LR=6.155829702431172e-05) Training Loss 0.076, ACC 0.979, macro AUROC 0.999.



 88%|████████▊ | 44/50 [1:02:24<08:24, 84.04s/it]

[[3.1556112e-07 9.9764013e-01 8.7905777e-10 2.3594804e-03]
 [8.4237687e-02 5.4169089e-01 3.3347678e-01 4.0594686e-02]
 [9.1918595e-02 6.4659864e-02 8.4062374e-01 2.7977906e-03]
 ...
 [9.7946745e-01 1.3229602e-04 2.0400289e-02 6.4726080e-10]
 [4.9228856e-01 1.3920914e-01 3.6849761e-01 4.6760556e-06]
 [2.4340006e-02 4.3540385e-01 5.4021400e-01 4.2112766e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.274, ACC 0.218, macro AUROC 0.627.


 14%|█▍        | 513/3610 [00:58<05:51,  8.81it/s]

Epoch 45/50: (LR=1.5413331334360186e-05) Training Loss 0.071, ACC 0.975, macro AUROC 0.999.



 90%|█████████ | 45/50 [1:03:49<07:01, 84.23s/it]

[[3.2180264e-07 9.9773008e-01 8.9732166e-10 2.2696168e-03]
 [8.3295591e-02 5.4671848e-01 3.3436072e-01 3.5625264e-02]
 [9.0431266e-02 6.1930813e-02 8.4526408e-01 2.3738437e-03]
 ...
 [9.8160166e-01 1.4453218e-04 1.8253779e-02 5.4138888e-10]
 [4.9350762e-01 1.5995638e-01 3.4653184e-01 4.1117378e-06]
 [2.3366768e-02 4.8065212e-01 4.9594295e-01 3.8226619e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.264, ACC 0.218, macro AUROC 0.623.


 14%|█▍        | 513/3610 [00:54<05:26,  9.48it/s]

Epoch 46/50: (LR=0.0) Training Loss 0.061, ACC 0.984, macro AUROC 0.999.



 92%|█████████▏| 46/50 [1:05:10<05:33, 83.43s/it]

[[3.1673235e-07 9.9774736e-01 8.9282498e-10 2.2522514e-03]
 [8.2841791e-02 5.4660273e-01 3.3506489e-01 3.5490595e-02]
 [9.0023622e-02 6.1453734e-02 8.4616727e-01 2.3553900e-03]
 ...
 [9.8129946e-01 1.4677172e-04 1.8553790e-02 5.4188842e-10]
 [4.8895490e-01 1.6091210e-01 3.5012892e-01 4.1033068e-06]
 [2.2712752e-02 4.7742128e-01 4.9982834e-01 3.7616672e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.255, ACC 0.222, macro AUROC 0.623.


 14%|█▍        | 513/3610 [00:56<05:42,  9.03it/s]

Epoch 47/50: (LR=1.541333133436018e-05) Training Loss 0.075, ACC 0.981, macro AUROC 0.999.



 94%|█████████▍| 47/50 [1:06:34<04:10, 83.33s/it]

[[3.1673144e-07 9.9774736e-01 8.9282159e-10 2.2522470e-03]
 [8.2842216e-02 5.4660255e-01 3.3506462e-01 3.5490554e-02]
 [9.0023398e-02 6.1453659e-02 8.4616762e-01 2.3553853e-03]
 ...
 [9.8129958e-01 1.4677047e-04 1.8553665e-02 5.4187921e-10]
 [4.8895580e-01 1.6091274e-01 3.5012740e-01 4.1032317e-06]
 [2.2712702e-02 4.7742009e-01 4.9982959e-01 3.7616479e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.255, ACC 0.222, macro AUROC 0.623.


 14%|█▍        | 513/3610 [00:57<05:46,  8.94it/s]

Epoch 48/50: (LR=6.155829702431336e-05) Training Loss 0.069, ACC 0.977, macro AUROC 0.999.



 96%|█████████▌| 48/50 [1:07:58<02:47, 83.53s/it]

[[3.1388186e-07 9.9785811e-01 8.9750185e-10 2.1415288e-03]
 [8.1407279e-02 5.4285914e-01 3.4207913e-01 3.3654444e-02]
 [8.5687168e-02 5.8959674e-02 8.5319132e-01 2.1618968e-03]
 ...
 [9.8079473e-01 1.4646363e-04 1.9058809e-02 5.2557031e-10]
 [4.8353919e-01 1.5888587e-01 3.5757089e-01 3.9799866e-06]
 [2.2120291e-02 4.6642035e-01 5.1142329e-01 3.6079746e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.254, ACC 0.222, macro AUROC 0.624.


 14%|█▍        | 513/3610 [00:55<05:34,  9.26it/s]

Epoch 49/50: (LR=0.00013815039801162162) Training Loss 0.049, ACC 0.981, macro AUROC 1.000.



 98%|█████████▊| 49/50 [1:09:20<01:23, 83.20s/it]

[[3.4028119e-07 9.9777287e-01 1.0397297e-09 2.2267525e-03]
 [8.0383480e-02 5.1524973e-01 3.7442738e-01 2.9939419e-02]
 [7.8956194e-02 5.2296516e-02 8.6693347e-01 1.8138011e-03]
 ...
 [9.8169506e-01 1.4162072e-04 1.8163260e-02 4.6080997e-10]
 [4.8366910e-01 1.5898387e-01 3.5734344e-01 3.6765066e-06]
 [2.1436041e-02 4.6226475e-01 5.1626462e-01 3.4588738e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.289, ACC 0.218, macro AUROC 0.624.


 14%|█▍        | 513/3610 [00:55<05:37,  9.17it/s]

Epoch 50/50: (LR=0.00024471741852424004) Training Loss 0.057, ACC 0.981, macro AUROC 1.000.



100%|██████████| 50/50 [1:10:43<00:00, 84.87s/it]

[[3.1156111e-07 9.9779189e-01 1.0144614e-09 2.2077027e-03]
 [8.3173156e-02 4.9851626e-01 3.8954747e-01 2.8763136e-02]
 [7.8959055e-02 4.3786455e-02 8.7574673e-01 1.5077017e-03]
 ...
 [9.8407817e-01 1.1838051e-04 1.5803520e-02 3.1928640e-10]
 [4.9818265e-01 1.4494783e-01 3.5686663e-01 2.8993197e-06]
 [2.0642577e-02 4.2216900e-01 5.5715775e-01 3.0691972e-05]]
[0 1 2 3]
y_pred has NaN: False
y_pred has inf: False
y_pred range: [0.000, 1.000]
Validation Loss 4.328, ACC 0.218, macro AUROC 0.626.
